### ISSUE TITLE
check version of Vue

### ISSUE THREAD

**Issue by SeregPie** [antfu/vue-demi#11]
Hi.
At first, great library and idea!

I have a feature request.
It would be nice to be able to check the version of the Vue because there are still some differences.

Something like this maybe.

```js
import {h, isVue2} from 'vue-demi';

h('div', {
  style: {/*...*/},
  ...(isVue2 ? {on: {click: onClick}} : {onClick}),
})
```

**Comment by antfu** [comment]
Mind creating a PR? Thanks.

**Comment by SeregPie** [comment]
Ok, will do that.
