### ISSUE TITLE
Does vue-demi support hard-link based package manager like pnpm ?

### ISSUE THREAD

**Issue by xialvjun** [antfu/vue-demi#17]

**Comment by antfu** [comment]
Yes for sure. I am using pnpm quite a lot myself. If you are facing any issue regarding them, just open an issue. Thanks.

**Comment by xialvjun** [comment]
But `vue-demi` change the file which in pnpm is hard link every project, then how can we use it in multi project .

**Comment by antfu** [comment]
Can you share a minimal reproduce repo?
