### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by peerone-frontend** [antfu/vue-demi#2]
Hi @antfu , i really like this project. 
But when i run `yarn build` in `examples/@vue-demi/use-mouse/` folder,  it had a problem.

<img width="1139" alt="截圖 2020-07-03 下午3 22 51" src="https://user-images.githubusercontent.com/66992583/86443036-423c6680-bd41-11ea-88bb-57a6d67014c5.png">

And i found this error in `examples/@vue-demi/use-mouse/src/index.ts`.
<img width="569" alt="截圖 2020-07-03 下午3 28 22" src="https://user-images.githubusercontent.com/66992583/86443454-de666d80-bd41-11ea-84b1-f9f989383dd7.png">

Have any solution to fix this? Thank you!

**Comment by antfu** [comment]
Did you install the deps?

**Comment by peerone-frontend** [comment]
Yes, i had installed deps in `@vue-demi/use-mouse/`
<img width="239" alt="截圖 2020-07-03 下午3 35 39" src="https://user-images.githubusercontent.com/66992583/86444217-060a0580-bd43-11ea-98a5-013b6118a7f9.png">

**Comment by antfu** [comment]
Thanks for spotting out. Released the fix v0.1.3. 

Please clean out node_modules and lock file then try again :)

**Comment by peerone-frontend** [comment]
Thank you very much.🥳
