### ISSUE TITLE
getCurrentInstance broken with Vue Composition API 1.0.0-beta.22

### ISSUE THREAD

**Issue by dm4t2** [antfu/vue-demi#23]
Hi @antfu, big thanks for providing Vue Demi.

Since the breaking change introduced in [Vue Composition API 1.0.0-beta.22](https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md#100-beta22-2020-12-19) `getCurrentInstance` only works with the following workaround in Vue 3:

```
const vm = isVue3 ? getCurrentInstance() : getCurrentInstance().proxy
const lazy = vm.attrs.modelModifiers.lazy // will crash with getCurrentInstance().proxy
```

**Comment by antfu** [comment]
Can you share a minimal repro repo? Thanks.

**Comment by dm4t2** [comment]
Vue 2: https://codesandbox.io/s/happy-ives-ybd68?file=/src/CustomInput.vue
Vue 3: https://codesandbox.io/s/solitary-fog-6irjl?file=/src/CustomInput.vue

With Vue 2 + Composition API 1.0.0-beta.22 the syntax has changed to
```
const vm = getCurrentInstance().proxy
```
This should be encapsulated by vue-demi since it does not work in Vue 3 or do I get something wrong here?

**Comment by antfu** [comment]
The breaking change introduced in the Vue 2 plugin is trying to align with Vue 3.

Your usage actually has multiple breaking changes in Vue 3 involved.

- `$listener` get removed in Vue 3 and present in `$attr`
- v-model changes
- vdom changes

This is really tricky to polyfill and it's not the responsibility of VCA plugin nor Vue Demi. I would suggest you use the `if (isVue2)` to handle the version-specific logic here, which is simpler and more clear.

**Comment by dm4t2** [comment]
Just realized that I mixed up the Vue 3 types `ComponentInternalInstance` and `ComponentPublicInstance` and now understanding the background of the alignment. Closing this. Thank you!
