### ISSUE TITLE
export 'defineComponent | computed | etc' was not found in 'vue'

### ISSUE THREAD

**Issue by alvarosaburido** [antfu/vue-demi#25]
Hi,  sorry that I'm creating a following issue to #22 but I don't have the right to re-open and I'm still a little bit stuck.

**Problem**

`"export 'defineComponent | computed |. etc' was not found in 'vue' ` 

Since  my library exports components created using  `defineComponent` it doesn't work in a  project  with `vue 2`
<img width="659" alt="Screenshot 2020-12-28 at 12 03 11" src="https://user-images.githubusercontent.com/4699008/103209997-b3ca2b80-4904-11eb-93de-b00897a7dd2d.png">

**Steps** 

1. I created a [PR](https://github.com/asigloo/vue-dynamic-forms/pull/211) to follow the process described in the `README.md` in my [library](https://github.com/asigloo/vue-dynamic-forms), changed `vue` imports to `vue-demi`, added the  `peerDependencies`, and installed everything.
2. Publish a new version [3.11.0](https://www.npmjs.com/package/@asigloo/vue-dynamic-forms/v/3.11.0)
3. In this  [branch](https://github.com/asigloo/vue-dynamic-forms/tree/feature/isomorph-installation) I installed  the last version on the `vue 2 demo` app --->  [link](https://github.com/asigloo/vue-dynamic-forms/tree/feature/isomorph-installation/demos/vue-2) 
4. Run `npm run serve`

If I understand correctly it's necessary to publish the npm package for vue-demi to work when installing on a  Vue 2 or  3  project, is not possible to test/debug locally without publishing it?. 

Thanks in advance

**Comment by antfu** [comment]
You can definitely use it without publishing.

Can't find the issue, did you external `vue-demi` from your bundle?

**Comment by alvarosaburido** [comment]
Do you mean using `vue-demi` in the `vue-2` app?

 I only installed `vue-demi` on the plugin root, not in the  vue-2 or vue-3 demos. 

I noticed when building the plugin with a `console.log` if `isVue2` is always false in the  result bundle

**Comment by alvarosaburido** [comment]
Hi, just an update from my side, I managed to get rid of the errors `export 'defineComponent | computed | etc' was not found in 'vue'` 

> Can't find the issue, did you external vue-demi from your bundle?

I finally understood what you mean @antfu, I updated my `rollup.config.js` to use `vue-demi` as external (similar to what @posva did in `vue-promised` [here](https://github.com/posva/vue-promised/blob/v2/rollup.config.js)) and that got rid of the errors but this one:

````
as-dynamic-forms.esm.js?3936:631 Uncaught TypeError: Object(...) is not a function
```

![Screenshot 2020-12-30 at 17 03 20](https://user-images.githubusercontent.com/4699008/103365686-ef115980-4ac0-11eb-80da-c115b36c1a13.png)

The only difference I see now is that I'm using `https://github.com/vuejs/rollup-plugin-vue` to bundle the `vue` files, I'm using a symlink to test locally but not sure if it's the best idea, do you have any suggestion on how could I test this? 

Thanks in advance.

**Comment by alvarosaburido** [comment]
Hi, @antfu I will close this issue since I found out that the origin of the problems are not related to your library but related to using `rollup-plugin-vue` in the build config.

My rough guess is that `rollup-plugin-vue` uses a specific version of vue because all errors prompt are related to rendering.

I open a [feature request](https://github.com/vuejs/rollup-plugin-vue/issues/427) on the `rollup-plugin-vue` repo for `vue-demi` to be used along with it. In the meantime, I will try to refactor all my components in my library to use `typescript` only.

If you want to play around with the reproduction repo, is this one https://github.com/alvarosaburido/vue-demi-universal-lib

Thanks and happy coding.
