### ISSUE TITLE
How to use if only Vue 3 is locally installed

### ISSUE THREAD

**Issue by posva** [antfu/vue-demi#27]
Hello, I'm struggling to update from 0.4 to 0.5 because I'm only using Vue 3 at https://github.com/posva/vue-use-spring and I get this TS error:

```
node_modules/vue-demi/lib/index.d.ts:4:31 - error TS2709: Cannot use namespace 'Vue' as a type.

4 declare const install: (vue?: Vue) => void
                                ~~~


Found 1 error.
```

I tried adding both vue2 and vue 3 like this: https://github.com/antfu/vueuse/blob/master/package.json but inversing them since I'm using Vue 3 inside of the project but it gave me even more errors 😓 

Do you have any idea of what I'm missing?

**Comment by antfu** [comment]
Fixed in 0ace336 and released as v0.5.4

**Comment by antfu** [comment]
And as for the co-existing, you can use Vue 3 as default and Vue 2 as `vue2`.
https://github.com/antfu/vueuse/blob/df6028f1585383f2d896fd79a8dd298dfa8e397e/package.json#L109-L110

**Comment by posva** [comment]
Thank you so much!
