### ISSUE TITLE
[v.6.0] Vue undefined while using reactive

### ISSUE THREAD

**Issue by lstoeferle** [antfu/vue-demi#28]
Hello @antfu,

I am facing a strange issue while using `v6.0 ` of the `vue-demi` package in my project. I have a global 'store' which can also be accessed outside of the Vue-context (e.g. in `main.ts`). The `Vue.use(VueCompositionApi)` call is made before calling any composition-api related functions.

```javascript
import { computed, reactive } from "@vue/composition-api"
import { toReadonlyState } from "@/utils/composition"

interface GeneralStore {
  token: string | null
  isAuthenticated: boolean
  isTranslationPresent: boolean
  translationError: boolean
}

const state = reactive<GeneralStore>({
  token: null,
  isAuthenticated: false,
  isTranslationPresent: false,
  translationError: false,
})

export function useGeneralStore() {
  const mutations = {
    setToken: (token?: string) => {
      state.token = token ?? null
    },
    setIsAuthenticated: (isAuthenticated: boolean) => {
      state.isAuthenticated = isAuthenticated
    },
    setIsTranslationPresent: (isTranslationPresent: boolean) => {
      state.isTranslationPresent = isTranslationPresent
    },
    setTranslationError: (translationError: boolean) => {
      state.translationError = translationError
    },
  }

  return {
    ...toReadonlyState(state),
    ...mutations,
  }
}

```

After upgrading vue-demi to `v6.0` the whole Vue2 application crashes on load with the following error:

```
Uncaught TypeError: Cannot read property 'observable' of undefined
  at ht (vue-composition-api.esm.js:563)
  ah gt (vue-composition-api.esm.js:673)
  ...
```

It seems Vue is undefined here...

```javascript
// vue-composition-api.esm.js
function reactive(obj) {
    if ((process.env.NODE_ENV !== 'production') && !obj) {
        warn('"reactive()" is called without provide an "object".');
        // @ts-ignore
        return;
    }
    if (!(isPlainObject(obj) || isArray(obj)) ||
        isRaw(obj) ||
        !Object.isExtensible(obj)) {
        return obj;
    }
    var observed = observe(obj); // FIXME: this call crashes due to Vue = undefined (line 673)
    setupAccessControl(observed);
    return observed;
}
```

```javascript
// vue-composition-api.esm.js
function observe(obj) {
    var Vue = getRegisteredVueOrDefault();
    var observed;
    if (Vue.observable) { // FIXME: Vue is undefined here (line 563)
        observed = Vue.observable(obj);
    }
    else {
        var vm = defineComponentInstance(Vue, {
            data: {
                $$state: obj,
            },
        });
        observed = vm._data.$$state;
    }
    // in SSR, there is no __ob__. Mock for reactivity check
    if (!hasOwn(observed, '__ob__')) {
        def(observed, '__ob__', mockObserver(observed));
    }
    return observed;
}
```

**Comment by antfu** [comment]
Could you share your `node_modules/vue-demi` archive? Thanks!

**Comment by lstoeferle** [comment]
Do you need files or is a screenshot enough for you?
![image](https://user-images.githubusercontent.com/48953604/104284982-37624b80-54b3-11eb-95b6-07fd299fcc8b.png)

I forgot to mention, that the Vue2 application works fine if I run it locally via `npm run serve`.

**Comment by antfu** [comment]
Humm, I need the files as `vue-demi` modifies them on installs.

Meanwhile, did you try this?

```diff
-import { computed, reactive } from "@vue/composition-api"
+import { computed, reactive } from "vue-demi"
import { toReadonlyState } from "@/utils/composition"
```

**Comment by lstoeferle** [comment]
I'm not directly using `vue-demi` in this project. I created a similar library like `vueuse` which uses `vue-demi` and this one is used in my SPA project. So it's maybe better if i send you the files from the library project?

**Comment by lstoeferle** [comment]
Here are the files from my "vueuse" project using `v0.6.0`.
[vue-demi.zip](https://github.com/antfu/vue-demi/files/5807747/vue-demi.zip)

**Comment by antfu** [comment]
Seem it get resolved correctly. My assumption it that you are using apis from `@vue/composition-api` before it get installed. `vue-demi` offered a util for you to ensure the installation, can you try to do this on the file you getting the error?

```js
import { install } from 'vue-demi'

install()

// use apis after install()
```

**Comment by lstoeferle** [comment]
Thanks for the hint 👍 I'll try as soon as I can find a time slot for it :)

**Comment by lstoeferle** [comment]
Hi @antfu,

I've solved the issue by adding `install` before the `reactive` call. You were right, the call happened before the installation of the composition api. 

Thanks for the hint ! 

```javascript
// FIX
install(Vue)

const state = reactive<GeneralStore>({
  token: null,
  isAuthenticated: false,
  isTranslationPresent: false,
  translationError: false
```
