### ISSUE TITLE
Move vue to peer dependencies

### ISSUE THREAD

**Issue by Demivan** [antfu/vue-demi#9]
`yarn@2` is now stricter about checking dependencies. It does not allow package to import dependency that is not in dependencies or peer dependencies. This causes runtime warnings or build errors.

Reproduction:
https://github.com/Demivan/vue-demi-dependencies
1. Checkout `vue-demi` branch
2. Run `yarn` 
3. Build with `yarn build`
4. Run built app with `yarn node bundle.js`
5. Get warning:
```
(node:68639) [MODULE_NOT_FOUND] Error: vue-demi tried to access vue, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
```
`master` branch uses fixed version of `vue-demi` with updated peer dependencies. With it warning is gone.

I have created proposed fix here: #8

**Comment by antfu** [comment]
Thanks for the PR
